name: Hello_World workflow
on:
  push:
    branches:
      -'main'
  pull_request:
    branches:
      -'main'
  workflow_dispatch:

jobs:
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: HI
        run: echo "HI THIS IS MAIN BRANCH WORKFLOW"
        shell: bash
