name: Hello_World workflow

on:
  push:
    branches:
      -main
  pull_request:
    branches:
      -main
  workflow_dispatch:

jobs:
  hello:
    runs_on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "Hello World"
        shell: bash
  goodbye:
    rus-on: ubuntu-latest
    steps:
      - name: goodbye
        run: echo "Good Bye!"
        shell: bash
